# Generated by Django 6.0.6 on 2026-06-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='correo',
        ),
    ]
